image:
  file: .devcontainer/Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
tasks:
- name: Run DB
  command: |
    docker compose up -f db 
- name: Workspace
  init: |
    pip install -r requirements.txt
    echo "Run 'uvicorn main:app --host 0.0.0.0 --port 8000' to run application"