image:
  file: .devcontainer/Dockerfile

vscode:
  extensions:
    - ms-python.debugpy
    - ms-python.python
    - cweijan.vscode-database-client2
    - cweijan.dbclient-jdbc

ports:
  - port: 8000
    visibility: private
  - port: 5432
    name: "PGSQL"
    visibility: private

tasks:
- name: Start App
  env:
    "PGDATA": "/home/gitpod/.local/pg-data"
    "PGDATABASE": "postgres"
    "PGUSER": "postgres"
    "PGPASSWORD": "postgres"
    "POSTGRES_DB": "postgres"
    "POSTGRES_USER": "postgres"
    "POSTGRES_PASSWORD": "postgres"
    "POSTGRES_HOST": "localhost"
  before: |
    direnv allow
  init: |
    /usr/lib/postgresql/13/bin/pg_ctl -o '-U postgres' initdb
    /usr/lib/postgresql/13/bin/pg_ctl start
    /usr/lib/postgresql/13/bin/psql -P pager=off -c 'select version();' 
    pip install -r requirements.txt
  command: |
    uvicorn main:app --host 0.0.0.0 --port 8000
