image:
  file: .devcontainer/Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
tasks:
- name: Start App
  env:
    "PGDATA": "/home/gitpod/.local/pg-data"
    "PGDATABASE": "postgres"
    "PGUSER": "postgres"
    "PGPASSWORD": "postgres"
    "POSTGRES_DB": "postgres"
    "POSTGRES_USER": "postgres"
    "POSTGRES_PASSWORD": "postgres"
    "POSTGRES_HOST": "localhost"
  before: |
    direnv allow
  init: |
    pg_ctl -o '-U postgres' initdb
    pg_ctl start
    psql -c 'select version();'
    pip install -r requirements.txt
  command: |
    uvicorn main:app --host 0.0.0.0 --port 8000
